name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux-cross-cswinrt:
    name: 'cross: Cross-build from Linux'
    strategy:
      matrix:
        arch: [i686, x86_64]
    runs-on: ubuntu-22.04
    env:
      CMAKE_COLOR_DIAGNOSTICS: 1
      CLICOLOR_FORCE: 1
    steps:
      - uses: actions/checkout@v6

      - name: Install cross compiler
        run: |
          arch=${{ matrix.arch }}
          sudo apt-get install g++-mingw-w64-${arch/_/-}
          sudo update-alternatives --set "${{ matrix.arch }}-w64-mingw32-gcc" "/usr/bin/${{ matrix.arch }}-w64-mingw32-gcc-posix"
          sudo update-alternatives --set "${{ matrix.arch }}-w64-mingw32-g++" "/usr/bin/${{ matrix.arch }}-w64-mingw32-g++-posix"

      - name: Cross-build cswinrt
        run: |
          cmake -S src/cswinrt/ -B build/cross/ --toolchain cross-mingw-toolchain.cmake \
            -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_CXX_FLAGS="-static" \
            -DCMAKE_INSTALL_PREFIX=$PWD/install/
          cmake --build build/cross/ --target install -j2

      - name: Upload cswinrt.exe
        uses: actions/upload-artifact@v6
        with:
          name: cross-build-${{ matrix.arch }}-bin
          path: install/bin/cswinrt.exe
